## Numpy

Импортировать NumPy под именем np

In [26]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [22]:
a0=np.zeros(10)
print(a0)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


Создать вектор размера 10, заполненный единицами

In [3]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

Создать вектор размера 10, заполненный числом 2.5

In [21]:
a=np.array([2.5]*10)
print (a)

[ 2.5  2.5  2.5  2.5  2.5  2.5  2.5  2.5  2.5  2.5]


Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [23]:
a0[4]=5
print (a0)

[ 0.  0.  0.  0.  5.  0.  0.  0.  0.  0.]


Развернуть вектор (первый становится последним)

In [46]:
b=np.random.random(15)
print (b)

print (np.flip(b,0))

[ 0.34429151  0.11891881  0.59306668  0.74426603  0.22641457  0.66920012
  0.11072019  0.53722035  0.31203819  0.94244157  0.67076899  0.28757891
  0.52232242  0.51540061  0.34083668]
[ 0.34083668  0.51540061  0.52232242  0.28757891  0.67076899  0.94244157
  0.31203819  0.53722035  0.11072019  0.66920012  0.22641457  0.74426603
  0.59306668  0.11891881  0.34429151]


Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [143]:
print (np.array([[0,1,2], [3,4,5],[6,7,8]]))

np.arange(0,9).reshape(3,3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [56]:
c=np.array([1,2,0,0,4,0])
c.nonzero()

(array([0, 1, 4], dtype=int64),)

Создать 3x3 единичную матрицу

In [98]:
a=np.ones(3)

cc=np.array([a,a,a])
cc1=np.ones([3,3])

print (cc)
print (cc1)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


Создать массив 3x3x3 со случайными значениями

In [103]:

cc=np.array([[np.random.random(3),np.random.random(3),np.random.random(3)],[np.random.random(3),np.random.random(3),np.random.random(3)],[np.random.random(3),np.random.random(3),np.random.random(3)]])
cc1=np.random.random([3,3,3])

print (cc)
print ('Или так :)')
print (cc1)

[[[ 0.6085273   0.31556279  0.71898008]
  [ 0.63791848  0.23950589  0.73234466]
  [ 0.70576272  0.82913818  0.06386204]]

 [[ 0.37724234  0.30742605  0.03608212]
  [ 0.04466255  0.94744254  0.47072302]
  [ 0.25117324  0.82035551  0.86849177]]

 [[ 0.631922    0.62678001  0.85357226]
  [ 0.98368694  0.23234433  0.46878947]
  [ 0.43717202  0.2555583   0.21555099]]]
Или так :)
[[[ 0.09588627  0.66877251  0.08159233]
  [ 0.15316078  0.07205968  0.23398356]
  [ 0.39481194  0.97147179  0.43431747]]

 [[ 0.24201488  0.28366548  0.26877106]
  [ 0.39486097  0.32553568  0.13932091]
  [ 0.93715255  0.77434096  0.78997379]]

 [[ 0.38705137  0.62449853  0.29851354]
  [ 0.97656051  0.72839944  0.15779298]
  [ 0.66595319  0.15165924  0.12411107]]]


Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [89]:
a30=np.random.random(30)
print (a30.mean())

0.435658691705


Перемножить матрицы 5x3 и 3x2

In [110]:
a1=np.random.random([5,3])
b1=np.random.random([3,2])
c1=a1.shape*b1

print (a1)
print (b1)
print (c1)

[[ 0.76763988  0.85809941  0.28623523]
 [ 0.53038555  0.92106587  0.83120858]
 [ 0.78133841  0.43033601  0.37003992]
 [ 0.73781196  0.37151642  0.13878873]
 [ 0.56563912  0.59211234  0.52170898]]
[[ 0.81526845  0.89605878]
 [ 0.40010379  0.85326496]
 [ 0.68491891  0.58056287]]
[[ 4.07634223  2.68817634]
 [ 2.00051896  2.55979488]
 [ 3.42459456  1.7416886 ]]


Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [315]:
a=np.linspace(0.01,0.99,10)
print (a)
print (a.shape)


[ 0.01        0.11888889  0.22777778  0.33666667  0.44555556  0.55444444
  0.66333333  0.77222222  0.88111111  0.99      ]
(10,)


Заменить максимальный элемент на ноль

In [134]:
a[a.argmax()]=0

print (a)

[ 0.01        0.11888889  0.22777778  0.33666667  0.44555556  0.55444444
  0.66333333  0.77222222  0.88111111  0.        ]


Преобразовать массив из float в int

In [139]:
a.astype(int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [37]:
a=np.arange(0,20).reshape(10,2)
def distance (a1):
    
    return list( map (np.sqrt, (map (np.sum,(a1-a)**2))))

print (a)

list(map(distance, a))


[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


[[0.0,
  2.8284271247461903,
  5.6568542494923806,
  8.4852813742385695,
  11.313708498984761,
  14.142135623730951,
  16.970562748477139,
  19.798989873223331,
  22.627416997969522,
  25.45584412271571],
 [2.8284271247461903,
  0.0,
  2.8284271247461903,
  5.6568542494923806,
  8.4852813742385695,
  11.313708498984761,
  14.142135623730951,
  16.970562748477139,
  19.798989873223331,
  22.627416997969522],
 [5.6568542494923806,
  2.8284271247461903,
  0.0,
  2.8284271247461903,
  5.6568542494923806,
  8.4852813742385695,
  11.313708498984761,
  14.142135623730951,
  16.970562748477139,
  19.798989873223331],
 [8.4852813742385695,
  5.6568542494923806,
  2.8284271247461903,
  0.0,
  2.8284271247461903,
  5.6568542494923806,
  8.4852813742385695,
  11.313708498984761,
  14.142135623730951,
  16.970562748477139],
 [11.313708498984761,
  8.4852813742385695,
  5.6568542494923806,
  2.8284271247461903,
  0.0,
  2.8284271247461903,
  5.6568542494923806,
  8.4852813742385695,
  11.31370849898

Случайно расположить p элементов в 2D массив

In [313]:
n = 10
p = 10
Z = np.zeros((n,n))
r=np.put(Z, np.random.choice(range(n*n), p, replace=False), 5)
print (Z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  5.  0.  0.  0.  0.  0.  0.  5.  0.]
 [ 0.  0.  0.  0.  5.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  5.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  5.  0.  0.  0.]
 [ 5.  0.  0.  0.  5.  0.  0.  0.  5.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  5.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 5.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [306]:
a0=np.zeros(3,dtype=int)
a1=np.arange(1,6)
 
i=a1.size -1

while i > 0:

    a1=np.insert(a1, i, a0, axis=0)
    i -= 1

print (a1)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


Найти наиболее частое значение в массиве

In [217]:
(values,index,counts)=np.unique(a1,return_index=True, return_counts=True)
ind = counts.argmax()
print (values[ind])


0


Найти n наибольших значений в массиве

In [312]:
#меняем исходный массив
a1=np.insert(a1,(4,6),3)
(values,index,counts)=np.unique(a1,return_index=True, return_counts=True)
n=2
print (values [np.argpartition(-counts,n)[:n]])

#изначально делал циклом
#ind = np.argpartition(-counts,n)[:n]
#aa=np.array([])
#for x in ind:
#    print (x)
#    aa=np.append(aa, values[x])
    
#print (values, counts, a1, aa)

[3 0]


## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [2]:
import pandas as pd
food=pd.DataFrame.from_csv('/Users/gat/Documents/otis/en.openfoodfacts.org.products.tsv', sep='\t')

C:\Program Files\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2821: DtypeWarning: Columns (3,5,19,20,24,25,26,27,28,36,37,38,39,48) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):


Посмотреть первые 5 записей

In [26]:
#food[:5]
food.head(5)

url  \
code                                                               
0000000003087  http://world-en.openfoodfacts.org/product/0000...   
0000000004530  http://world-en.openfoodfacts.org/product/0000...   
0000000004559  http://world-en.openfoodfacts.org/product/0000...   
0000000016087  http://world-en.openfoodfacts.org/product/0000...   
0000000016094  http://world-en.openfoodfacts.org/product/0000...   

                                  creator   created_t      created_datetime  \
code                                                                          
0000000003087  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
0000000004530             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
0000000004559             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
0000000016087             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
0000000016094             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

              last_modified_t last_modified_datetime  \
code                                                   
0000000003087      1474103893   2016-09-17T09:18:13Z   
0000000004530      1489069957   2017-03-09T14:32:37Z   
0000000004559      1489069957   2017-03-09T14:32:37Z   
0000000016087      1489055731   2017-03-09T10:35:31Z   
0000000016094      1489055653   2017-03-09T10:34:13Z   

                                 product_name generic_name quantity packaging  \
code                                                                            
0000000003087              Farine de blé noir          NaN      1kg       NaN   
0000000004530  Banana Chips Sweetened (Whole)          NaN      NaN       NaN   
0000000004559                         Peanuts          NaN      NaN       NaN   
0000000016087          Organic Salted Nut Mix          NaN      NaN       NaN   
0000000016094                 Organic Polenta          NaN      NaN       NaN   

                      ...         fruits-vegetables-nuts_100g  \
code                  ...                                       
0000000003087         ...                                 NaN   
0000000004530         ...                                 NaN   
0000000004559         ...                                 NaN   
0000000016087         ...                                 NaN   
0000000016094         ...                                 NaN   

              fruits-vegetables-nuts-estimate_100g  \
code                                                 
0000000003087                                  NaN   
0000000004530                                  NaN   
0000000004559                                  NaN   
0000000016087                                  NaN   
0000000016094                                  NaN   

              collagen-meat-protein-ratio_100g cocoa_100g chlorophyl_100g  \
code                                                                        
0000000003087                              NaN        NaN             NaN   
0000000004530                              NaN        NaN             NaN   
0000000004559                              NaN        NaN             NaN   
0000000016087                              NaN        NaN             NaN   
0000000016094                              NaN        NaN             NaN   

              carbon-footprint_100g nutrition-score-fr_100g  \
code                                                          
0000000003087                   NaN                     NaN   
0000000004530                   NaN                    14.0   
0000000004559                   NaN                     0.0   
0000000016087                   NaN                    12.0   
0000000016094                   NaN                     NaN   

              nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
code                                                                           
0000000003087                     NaN                 NaN                 NaN  
000000000453

Сколько наблюдений в наборе данных?


In [37]:
food.index.size

356027

Сколько столбцов в наборе данных?

In [36]:
food.columns.size

162

Напечатайте все названия столбцов

In [48]:
food.columns.values

array(['url', 'creator', 'created_t', 'created_datetime',
       'last_modified_t', 'last_modified_datetime', 'product_name',
       'generic_name', 'quantity', 'packaging', 'packaging_tags', 'brands',
       'brands_tags', 'categories', 'categories_tags', 'categories_en',
       'origins', 'origins_tags', 'manufacturing_places',
       'manufacturing_places_tags', 'labels', 'labels_tags', 'labels_en',
       'emb_codes', 'emb_codes_tags', 'first_packaging_code_geo', 'cities',
       'cities_tags', 'purchase_places', 'stores', 'countries',
       'countries_tags', 'countries_en', 'ingredients_text', 'allergens',
       'allergens_en', 'traces', 'traces_tags', 'traces_en',
       'serving_size', 'no_nutriments', 'additives_n', 'additives',
       'additives_tags', 'additives_en', 'ingredients_from_palm_oil_n',
       'ingredients_from_palm_oil', 'ingredients_from_palm_oil_tags',
       'ingredients_that_may_be_from_palm_oil_n',
       'ingredients_that_may_be_from_palm_oil',
       'ing

Какое название у 105 столбца?

In [58]:
food.columns.values[105]

'-lactose_100g'

Какой тип наблюдений в 105 столбце?

In [63]:
food.dtypes[105]

dtype('float64')

Как проиндексирован набор данных?

In [64]:
food.reindex

<bound method DataFrame.reindex of                                                              url  \
code                                                               
0000000003087  http://world-en.openfoodfacts.org/product/0000...   
0000000004530  http://world-en.openfoodfacts.org/product/0000...   
0000000004559  http://world-en.openfoodfacts.org/product/0000...   
0000000016087  http://world-en.openfoodfacts.org/product/0000...   
0000000016094  http://world-en.openfoodfacts.org/product/0000...   
0000000016100  http://world-en.openfoodfacts.org/product/0000...   
0000000016117  http://world-en.openfoodfacts.org/product/0000...   
0000000016124  http://world-en.openfoodfacts.org/product/0000...   
0000000016193  http://world-en.openfoodfacts.org/product/0000...   
0000000016513  http://world-en.openfoodfacts.org/product/0000...   
0000000016612  http://world-en.openfoodfacts.org/product/0000...   
0000000016650  http://world-en.openfoodfacts.org/product/0000...   
0000000016872

Каково значение имени продукта в 19-м наблюдении?

In [86]:
food.product_name.iloc[18:19]

code
0000000018197    Lotus Organic Brown Jasmine Rice
Name: product_name, dtype: object

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [3]:
url='https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
chipo=pd.DataFrame.from_csv(url, sep='\t')

Как много продуктов стоят более чем $10.00?

In [4]:
#chipo ['item_price'] =pd.DataFrame.astype(chipo.item_price.str.strip(to_strip='$'),dtype='float')
#chipo.item_price.astype('int32')

chipo[ pd.DataFrame.astype(chipo.item_price.str.strip(to_strip='$'),dtype='float') > 10].count()
#chipo.dtypes

#chipo[[item_price] > 10]


quantity              1130
item_name             1130
choice_description    1123
item_price            1130
dtype: int64

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [132]:
col=['item_name','item_price']
chipo[col]

item_name item_price
order_id                                                  
1                  Chips and Fresh Tomato Salsa     $2.39 
1                                          Izze     $3.39 
1                              Nantucket Nectar     $3.39 
1         Chips and Tomatillo-Green Chili Salsa     $2.39 
2                                  Chicken Bowl    $16.98 
3                                  Chicken Bowl    $10.98 
3                                 Side of Chips     $1.69 
4                                 Steak Burrito    $11.75 
4                              Steak Soft Tacos     $9.25 
5                                 Steak Burrito     $9.25 
5                           Chips and Guacamole     $4.45 
6                          Chicken Crispy Tacos     $8.75 
6                            Chicken Soft Tacos     $8.75 
7                                  Chicken Bowl    $11.25 
7                           Chips and Guacamole     $4.45 
8         Chips and Tomatillo-Green Chili Salsa     $2.39 
8                               Chicken Burrito     $8.49 
9                               Chicken Burrito     $8.49 
9                                   Canned Soda     $2.18 
10                                 Chicken Bowl     $8.75 
10                          Chips and Guacamole     $4.45 
11                             Barbacoa Burrito     $8.99 
11                             Nantucket Nectar     $3.39 
12                              Chicken Burrito    $10.98 
12                                         Izze     $3.39 
13                 Chips and Fresh Tomato Salsa     $2.39 
13                                 Chicken Bowl     $8.49 
14                             Carnitas Burrito     $8.99 
14                                  Canned Soda     $1.09 
15                              Chicken Burrito     $8.49 
...                                         ...        ...
1825                           Barbacoa Burrito    $11.75 
1825                              Carnitas Bowl    $11.75 
1825                              Barbacoa Bowl    $11.75 
1826                               Chicken Bowl     $8.75 
1826                        Chips and Guacamole     $4.45 
1826                          Canned Soft Drink     $1.25 
1826                              Bottled Water     $1.50 
1827                               Chicken Bowl     $8.75 
1827                        Chips and Guacamole     $4.45 
1827                          Canned Soft Drink     $1.25 
1827                           Barbacoa Burrito     $9.25 
1827                           Barbacoa Burrito     $9.25 
1828                               Chicken Bowl     $8.75 
1828                        Chips and Guacamole     $4.45 
1828                          Canned Soft Drink     $1.25 
1829                              Steak Burrito    $11.75 
1829                             Veggie Burrito    $11.25 
1829                          Canned Soft Drink     $1.25 
1830                              Steak Burrito    $11.75 
1830                             Veggie Burrito    $11.25 
1831                              Carnitas Bowl     $9.25 
1831                                      Chips     $2.15 
1831                              Bottled Water     $1.50 
1832                         Chicken Soft Tacos     $8.75 
1832                        Chips and Guacamole     $4.45 
1833                              Steak Burrito    $11.75 
1833                              Steak Burrito    $11.75 
1834                         Chicken Salad Bowl    $11.25 
1834                         Chicken Salad Bowl     $8.75 
1834                         Chicken Salad Bowl     $8.75 

[4622 rows x 2 columns]

Отсортировать по имени предмета

In [123]:
chipo.sort_values('item_name')

quantity          item_name  \
order_id                                
1360             2  6 Pack Soft Drink   
148              1  6 Pack Soft Drink   
749              1  6 Pack Soft Drink   
754              1  6 Pack Soft Drink   
1076             1  6 Pack Soft Drink   
1373             1  6 Pack Soft Drink   
230              1  6 Pack Soft Drink   
774              1  6 Pack Soft Drink   
776              1  6 Pack Soft Drink   
784              1  6 Pack Soft Drink   
1537             1  6 Pack Soft Drink   
129              1  6 Pack Soft Drink   
798              1  6 Pack Soft Drink   
481              1  6 Pack Soft Drink   
1554             1  6 Pack Soft Drink   
465              1  6 Pack Soft Drink   
1558             1  6 Pack Soft Drink   
849              1  6 Pack Soft Drink   
1196             1  6 Pack Soft Drink   
1803             1  6 Pack Soft Drink   
1664             1  6 Pack Soft Drink   
1666             1  6 Pack Soft Drink   
1800             1  6 Pack Soft Drink   
1798             1  6 Pack Soft Drink   
1525             1  6 Pack Soft Drink   
949              1  6 Pack Soft Drink   
1248             1  6 Pack Soft Drink   
1253             1  6 Pack Soft Drink   
264              1  6 Pack Soft Drink   
422              1  6 Pack Soft Drink   
...            ...                ...   
1192             1       Veggie Salad   
1263             1       Veggie Salad   
1635             1       Veggie Salad   
686              1       Veggie Salad   
1094             1       Veggie Salad   
1677             1  Veggie Salad Bowl   
760              1  Veggie Salad Bowl   
195              1  Veggie Salad Bowl   
1289             1  Veggie Salad Bowl   
896              1  Veggie Salad Bowl   
913              1  Veggie Salad Bowl   
1805             1  Veggie Salad Bowl   
1321             1  Veggie Salad Bowl   
83               1  Veggie Salad Bowl   
394              1  Veggie Salad Bowl   
536              1  Veggie Salad Bowl   
869              1  Veggie Salad Bowl   
1700             1  Veggie Salad Bowl   
128              1  Veggie Salad Bowl   
1818             1  Veggie Salad Bowl   
1066             1  Veggie Salad Bowl   
207              1  Veggie Salad Bowl   
1646             1  Veggie Salad Bowl   
304              1  Veggie Soft Tacos   
1559             2  Veggie Soft Tacos   
948              1  Veggie Soft Tacos   
322              1  Veggie Soft Tacos   
1132             1  Veggie Soft Tacos   
688              1  Veggie Soft Tacos   
567              1  Veggie Soft Tacos   

                                         choice_description item_price  
order_id                                                                
1360                                            [Diet Coke]    $12.98   
148                                             [Diet Coke]     $6.49   
749                                                  [Coke]     $6.49   
754                                             [Diet Coke]     $6.49   
1076                                                 [Coke]     $6.49   
1373                                                 [Coke]     $6.49   
230                                             [Diet Coke]     $6.49   
774                                             [Diet Coke]     $6.49   
776                                                  [Coke]     $6.49   
784                                             [Diet Coke]     $6.49   
1537                                                 [Coke]     $6.49   
129                                                [Sprite]     $6.49   
798                                             [Diet Coke]     $6.49   
481                                                  [Coke]     $6.49   
1554                                            [Diet Coke]     $6.49   
465                                                  [Coke]     $6.49   
1558                                            [Diet Coke]     $6.49   
849                                    

Сколько было заказано самого дорогого предмета?

In [243]:
chipo['price']=chipo.item_price.str.strip(to_strip='$')
chipo[(chipo.price.astype('float').values) == (chipo.price.astype('float').max())].count()
#chipo.item_price.describe()

quantity              1
item_name             1
choice_description    0
item_price            1
price                 1
dtype: int64

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [276]:
chipo.item_name.value_counts()['Veggie Salad Bowl']

18

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [25]:
chipo_caned_soda=chipo[((chipo.item_name == 'Canned Soda') & (chipo.quantity.astype('float')>1))]

chipo_caned_soda.item_name.count()

#chipo.groupby

20